
org $FFFFDA : DW archipelago_chozo_item_plm 	: skip 2 : DW $0000
org $FFFF9C : DW archipelago_chozo_item_plm 	: skip 2 : DW $0000
org $FFFF64 : DW archipelago_chozo_item_plm 	: skip 2 : DW $0000
org $FFFFF2 : DW archipelago_chozo_item_plm 	: skip 2 : DW $0001
org $FFFFAE : DW archipelago_chozo_item_plm 	: skip 2 : DW $0001
org $FFFF12 : DW archipelago_visible_item_plm 	: skip 2 : DW $0002
org $FFFDF6 : DW archipelago_chozo_item_plm 	: skip 2 : DW $0003
org $FFFDD6 : DW archipelago_hidden_item_plm	: skip 2 : DW $0004
org $FFFDC2 : DW archipelago_hidden_item_plm	: skip 2 : DW $0004
org $FFFDDC : DW archipelago_hidden_item_plm	: skip 2 : DW $0005
org $FFFDC8 : DW archipelago_hidden_item_plm	: skip 2 : DW $0005
org $FFFD54 : DW archipelago_chozo_item_plm 	: skip 2 : DW $0006
org $FFFCE8 : DW archipelago_hidden_item_plm	: skip 2 : DW $0007
org $FFFC5C : DW archipelago_chozo_item_plm 	: skip 2 : DW $0008
org $FFFC48 : DW archipelago_visible_item_plm 	: skip 2 : DW $0009
org $FFFC06 : DW archipelago_chozo_item_plm 	: skip 2 : DW $000A
org $FFFC06 : DW archipelago_chozo_item_plm 	: skip 2 : DW $000A
org $FFFBE6 : DW archipelago_chozo_item_plm 	: skip 2 : DW $000B
org $FFFB92 : DW archipelago_chozo_item_plm 	: skip 2 : DW $000C
org $FFFB26 : DW archipelago_chozo_item_plm 	: skip 2 : DW $000D
org $FFFAFA : DW archipelago_chozo_item_plm 	: skip 2 : DW $000E
org $FFFAFA : DW archipelago_chozo_item_plm 	: skip 2 : DW $000E
org $FFFA98 : DW archipelago_hidden_item_plm	: skip 2 : DW $000F
org $FFFA54 : DW archipelago_chozo_item_plm 	: skip 2 : DW $0010
org $FFFA54 : DW archipelago_chozo_item_plm 	: skip 2 : DW $0010
org $FFF90E : DW archipelago_chozo_item_plm 	: skip 2 : DW $0011
org $FFF8B8 : DW archipelago_chozo_item_plm 	: skip 2 : DW $0012
org $FFF8A4 : DW archipelago_chozo_item_plm 	: skip 2 : DW $0012
org $FFF86A : DW archipelago_chozo_item_plm 	: skip 2 : DW $0013
org $FFF7E8 : DW archipelago_chozo_item_plm 	: skip 2 : DW $0014
org $FFF7CE : DW archipelago_chozo_item_plm 	: skip 2 : DW $0015
org $FFF780 : DW archipelago_chozo_item_plm 	: skip 2 : DW $0016
org $FFF786 : DW archipelago_chozo_item_plm 	: skip 2 : DW $0017
org $FFF78C : DW archipelago_hidden_item_plm	: skip 2 : DW $0018
org $FFF760 : DW archipelago_visible_item_plm 	: skip 2 : DW $0019
org $FFF74C : DW archipelago_chozo_item_plm 	: skip 2 : DW $001A
org $FFF73E : DW archipelago_hidden_item_plm	: skip 2 : DW $001B
org $FFF6E0 : DW archipelago_chozo_item_plm 	: skip 2 : DW $001C
org $FFF608 : DW archipelago_chozo_item_plm 	: skip 2 : DW $001D
org $FFF600 : DW archipelago_chozo_item_plm 	: skip 2 : DW $001E
org $FFF5F2 : DW archipelago_visible_item_plm 	: skip 2 : DW $001F
org $FFF5CC : DW archipelago_chozo_item_plm 	: skip 2 : DW $0020
org $FFF5D2 : DW archipelago_chozo_item_plm 	: skip 2 : DW $0021
org $FFF5A6 : DW archipelago_chozo_item_plm 	: skip 2 : DW $0022
org $FFF5C4 : DW archipelago_chozo_item_plm 	: skip 2 : DW $0023
org $FFF578 : DW archipelago_hidden_item_plm	: skip 2 : DW $0024
org $FFF4DA : DW archipelago_chozo_item_plm 	: skip 2 : DW $0025
org $FFF9C2 : DW archipelago_visible_item_plm 	: skip 2 : DW $0026
org $FFF3C4 : DW archipelago_visible_item_plm 	: skip 2 : DW $0026
org $FFF350 : DW archipelago_chozo_item_plm 	: skip 2 : DW $0027
org $FFF318 : DW archipelago_visible_item_plm 	: skip 2 : DW $0028
org $FFF29A : DW archipelago_visible_item_plm 	: skip 2 : DW $0029
org $FFF22E : DW archipelago_chozo_item_plm 	: skip 2 : DW $002A
org $FFF0CA : DW archipelago_visible_item_plm 	: skip 2 : DW $002B
org $FFEF94 : DW archipelago_hidden_item_plm	: skip 2 : DW $002C
org $FFEF86 : DW archipelago_hidden_item_plm	: skip 2 : DW $002C
org $FFEF86 : DW archipelago_hidden_item_plm	: skip 2 : DW $002C
org $FFEF3E : DW archipelago_visible_item_plm 	: skip 2 : DW $002D
org $FFEE28 : DW archipelago_chozo_item_plm 	: skip 2 : DW $002E
org $FFEE0E : DW archipelago_hidden_item_plm	: skip 2 : DW $002F
org $FFEDFE : DW archipelago_chozo_item_plm 	: skip 2 : DW $0030
org $FFED6E : DW archipelago_visible_item_plm 	: skip 2 : DW $0031
org $FFEC64 : DW archipelago_visible_item_plm 	: skip 2 : DW $0032
org $FFEC4A : DW archipelago_visible_item_plm 	: skip 2 : DW $0032
org $FFEC1C : DW archipelago_visible_item_plm 	: skip 2 : DW $0033
org $FFEB8A : DW archipelago_hidden_item_plm	: skip 2 : DW $0034
org $FFEAAA : DW archipelago_chozo_item_plm 	: skip 2 : DW $0035
org $FFEA5E : DW archipelago_chozo_item_plm 	: skip 2 : DW $0036
org $FFEA0C : DW archipelago_chozo_item_plm 	: skip 2 : DW $0037
org $FFE990 : DW archipelago_chozo_item_plm 	: skip 2 : DW $0037
org $FFE90A : DW archipelago_hidden_item_plm	: skip 2 : DW $0038
org $FFE8E8 : DW archipelago_visible_item_plm 	: skip 2 : DW $0039
org $FFE8D0 : DW archipelago_chozo_item_plm 	: skip 2 : DW $003A
org $FFE85E : DW archipelago_chozo_item_plm 	: skip 2 : DW $003B
org $FFE836 : DW archipelago_visible_item_plm 	: skip 2 : DW $003C
org $FFE818 : DW archipelago_hidden_item_plm	: skip 2 : DW $003D
org $FFE71C : DW archipelago_chozo_item_plm 	: skip 2 : DW $003E
org $FFE708 : DW archipelago_chozo_item_plm 	: skip 2 : DW $003F
org $FFE6F4 : DW archipelago_visible_item_plm 	: skip 2 : DW $0040
org $FFE6D6 : DW archipelago_visible_item_plm 	: skip 2 : DW $0041
org $FFE6BA : DW archipelago_visible_item_plm 	: skip 2 : DW $0042
org $FFE628 : DW archipelago_chozo_item_plm 	: skip 2 : DW $0043
org $FFE628 : DW archipelago_chozo_item_plm 	: skip 2 : DW $0043
org $FFE5FC : DW archipelago_visible_item_plm 	: skip 2 : DW $0044
org $FFE5F4 : DW archipelago_visible_item_plm 	: skip 2 : DW $0044
org $FFE586 : DW archipelago_hidden_item_plm	: skip 2 : DW $0045
org $FFE57E : DW archipelago_visible_item_plm 	: skip 2 : DW $0046
org $FFE4F8 : DW archipelago_visible_item_plm 	: skip 2 : DW $0047
org $FFE4F8 : DW archipelago_visible_item_plm 	: skip 2 : DW $0047
org $FFE4A2 : DW archipelago_chozo_item_plm 	: skip 2 : DW $0048
org $FFE4A2 : DW archipelago_chozo_item_plm 	: skip 2 : DW $0048
org $FFE494 : DW archipelago_hidden_item_plm	: skip 2 : DW $0049
org $FFE480 : DW archipelago_hidden_item_plm	: skip 2 : DW $0049
org $FFE40E : DW archipelago_chozo_item_plm 	: skip 2 : DW $004A
org $FFE40E : DW archipelago_chozo_item_plm 	: skip 2 : DW $004A
org $FFE414 : DW archipelago_chozo_item_plm 	: skip 2 : DW $004B
org $FFE414 : DW archipelago_chozo_item_plm 	: skip 2 : DW $004B
org $FFE3E8 : DW archipelago_visible_item_plm 	: skip 2 : DW $004C
org $FFE3E8 : DW archipelago_visible_item_plm 	: skip 2 : DW $004C
org $FFE3C0 : DW archipelago_visible_item_plm 	: skip 2 : DW $004D
org $FFE3C0 : DW archipelago_visible_item_plm 	: skip 2 : DW $004D
org $FFE3B2 : DW archipelago_visible_item_plm 	: skip 2 : DW $004E
org $FFE3B2 : DW archipelago_visible_item_plm 	: skip 2 : DW $004E
org $FFE384 : DW archipelago_chozo_item_plm 	: skip 2 : DW $004F
org $FFE384 : DW archipelago_chozo_item_plm 	: skip 2 : DW $004F
org $FFE326 : DW archipelago_hidden_item_plm	: skip 2 : DW $0050
org $FFE2EE : DW archipelago_chozo_item_plm 	: skip 2 : DW $0051
org $FFE30C : DW archipelago_visible_item_plm 	: skip 2 : DW $0052
org $FFE2D6 : DW archipelago_chozo_item_plm 	: skip 2 : DW $0053
org $FFE294 : DW archipelago_chozo_item_plm 	: skip 2 : DW $0054
org $FFE24E : DW archipelago_visible_item_plm 	: skip 2 : DW $0055
org $FFE17A : DW archipelago_chozo_item_plm 	: skip 2 : DW $0056
org $FFE146 : DW archipelago_chozo_item_plm 	: skip 2 : DW $0056
org $FFE138 : DW archipelago_hidden_item_plm	: skip 2 : DW $0057
org $FFE0EE : DW archipelago_chozo_item_plm 	: skip 2 : DW $0058
org $FFE0B8 : DW archipelago_hidden_item_plm	: skip 2 : DW $0059
org $FFDF70 : DW archipelago_chozo_item_plm 	: skip 2 : DW $005A
org $FFDF68 : DW archipelago_chozo_item_plm 	: skip 2 : DW $005A
org $FFDF76 : DW archipelago_visible_item_plm 	: skip 2 : DW $005B
org $FFDF7C : DW archipelago_visible_item_plm 	: skip 2 : DW $005C
org $FFDEA6 : DW archipelago_chozo_item_plm 	: skip 2 : DW $005D
org $FFDE80 : DW archipelago_visible_item_plm 	: skip 2 : DW $005E
org $FFDE40 : DW archipelago_chozo_item_plm 	: skip 2 : DW $005F
org $FFDE32 : DW archipelago_chozo_item_plm 	: skip 2 : DW $0060
org $FFDE2A : DW archipelago_visible_item_plm 	: skip 2 : DW $0061
org $FFDE10 : DW archipelago_visible_item_plm 	: skip 2 : DW $0062
org $FFDD88 : DW archipelago_visible_item_plm 	: skip 2 : DW $0063
org $FFDD6E : DW archipelago_visible_item_plm 	: skip 2 : DW $0063
org $FFDC3E : DW archipelago_chozo_item_plm 	: skip 2 : DW $0064
org $FFDBFA : DW archipelago_chozo_item_plm 	: skip 2 : DW $0065
org $FFDBF2 : DW archipelago_chozo_item_plm 	: skip 2 : DW $0066
org $FFDBE0 : DW archipelago_visible_item_plm 	: skip 2 : DW $0067
org $FFDBD2 : DW archipelago_chozo_item_plm 	: skip 2 : DW $0068
org $FFD132 : DW archipelago_visible_item_plm 	: skip 2 : DW $0069
org $FFD0FE : DW archipelago_visible_item_plm 	: skip 2 : DW $0069
org $FFD0E0 : DW archipelago_chozo_item_plm 	: skip 2 : DW $006A
org $FFDE08 : DW archipelago_visible_item_plm 	: skip 2 : DW $006B
org $FFFEA6 : DW archipelago_hidden_item_plm	: skip 2 : DW $006C
org $FFFEAE : DW archipelago_hidden_item_plm	: skip 2 : DW $006D
org $FFED34 : DW archipelago_chozo_item_plm 	: skip 2 : DW $006E
org $FFFE0C : DW archipelago_hidden_item_plm	: skip 2 : DW $006F
org $FFDBB0 : DW archipelago_chozo_item_plm 	: skip 2 : DW $0070
org $FFD958 : DW archipelago_visible_item_plm 	: skip 2 : DW $0071
org $FFD8E0 : DW archipelago_hidden_item_plm	: skip 2 : DW $0072
org $FFD88C : DW archipelago_visible_item_plm 	: skip 2 : DW $0073
org $FFD868 : DW archipelago_visible_item_plm 	: skip 2 : DW $0074
org $FFD7CE : DW archipelago_chozo_item_plm 	: skip 2 : DW $0075
org $FFD62E : DW archipelago_chozo_item_plm 	: skip 2 : DW $0076
org $FFD60A : DW archipelago_chozo_item_plm 	: skip 2 : DW $0077
org $FFD3F2 : DW archipelago_chozo_item_plm 	: skip 2 : DW $0078
org $FFD3E2 : DW archipelago_hidden_item_plm	: skip 2 : DW $0079
org $FFD4B2 : DW archipelago_visible_item_plm 	: skip 2 : DW $007A
org $FFD254 : DW archipelago_visible_item_plm 	: skip 2 : DW $007B
org $FFD226 : DW archipelago_hidden_item_plm	: skip 2 : DW $007C
org $FFD3B8 : DW archipelago_visible_item_plm 	: skip 2 : DW $007D
org $FFD316 : DW archipelago_hidden_item_plm	: skip 2 : DW $007E
org $FFD264 : DW archipelago_visible_item_plm 	: skip 2 : DW $007F
org $FFD1B8 : DW archipelago_chozo_item_plm 	: skip 2 : DW $0080
org $FFE27C : DW archipelago_visible_item_plm 	: skip 2 : DW $0081
org $FFE274 : DW archipelago_visible_item_plm 	: skip 2 : DW $0081
org $FFFC54 : DW archipelago_hidden_item_plm	: skip 2 : DW $00C6
